/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Chapter = IDL.Record({
  'sanskritSubtitle' : IDL.Text,
  'englishTitle' : IDL.Text,
  'verseCount' : IDL.Nat,
  'keyInsights' : IDL.Vec(IDL.Text),
  'summary' : IDL.Text,
  'number' : IDL.Nat,
});
export const Mood = IDL.Variant({
  'sad' : IDL.Null,
  'anxious' : IDL.Null,
  'angry' : IDL.Null,
  'calm' : IDL.Null,
  'lost' : IDL.Null,
  'motivated' : IDL.Null,
});
export const Verse = IDL.Record({
  'hindiMeaning' : IDL.Text,
  'verse' : IDL.Nat,
  'actionStep' : IDL.Text,
  'englishMeaning' : IDL.Text,
  'chapter' : IDL.Nat,
  'genZKrishnaInterpretation' : IDL.Text,
  'sanskrit' : IDL.Text,
});
export const ChatbotResponse = IDL.Record({
  'selectedVerse' : Verse,
  'supportiveMessage' : IDL.Text,
  'actionStep' : IDL.Text,
  'followUpQuestions' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'getAllChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
  'getChatbotResponse' : IDL.Func(
      [IDL.Text, IDL.Opt(Mood), IDL.Vec(IDL.Text)],
      [ChatbotResponse],
      [],
    ),
  'getCuratedVersesByMood' : IDL.Func([Mood], [IDL.Vec(Verse)], ['query']),
  'getMoodTaglines' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Mood, IDL.Text))],
      ['query'],
    ),
  'getTodaysVerse' : IDL.Func([], [Verse], ['query']),
  'getVerse' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(Verse)], ['query']),
  'getVersesByChapter' : IDL.Func([IDL.Nat], [IDL.Vec(Verse)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Chapter = IDL.Record({
    'sanskritSubtitle' : IDL.Text,
    'englishTitle' : IDL.Text,
    'verseCount' : IDL.Nat,
    'keyInsights' : IDL.Vec(IDL.Text),
    'summary' : IDL.Text,
    'number' : IDL.Nat,
  });
  const Mood = IDL.Variant({
    'sad' : IDL.Null,
    'anxious' : IDL.Null,
    'angry' : IDL.Null,
    'calm' : IDL.Null,
    'lost' : IDL.Null,
    'motivated' : IDL.Null,
  });
  const Verse = IDL.Record({
    'hindiMeaning' : IDL.Text,
    'verse' : IDL.Nat,
    'actionStep' : IDL.Text,
    'englishMeaning' : IDL.Text,
    'chapter' : IDL.Nat,
    'genZKrishnaInterpretation' : IDL.Text,
    'sanskrit' : IDL.Text,
  });
  const ChatbotResponse = IDL.Record({
    'selectedVerse' : Verse,
    'supportiveMessage' : IDL.Text,
    'actionStep' : IDL.Text,
    'followUpQuestions' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'getAllChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
    'getChatbotResponse' : IDL.Func(
        [IDL.Text, IDL.Opt(Mood), IDL.Vec(IDL.Text)],
        [ChatbotResponse],
        [],
      ),
    'getCuratedVersesByMood' : IDL.Func([Mood], [IDL.Vec(Verse)], ['query']),
    'getMoodTaglines' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Mood, IDL.Text))],
        ['query'],
      ),
    'getTodaysVerse' : IDL.Func([], [Verse], ['query']),
    'getVerse' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(Verse)], ['query']),
    'getVersesByChapter' : IDL.Func([IDL.Nat], [IDL.Vec(Verse)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };