/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chapter {
  'sanskritSubtitle' : string,
  'englishTitle' : string,
  'verseCount' : bigint,
  'keyInsights' : Array<string>,
  'summary' : string,
  'number' : bigint,
}
export interface ChatbotResponse {
  'selectedVerse' : [] | [Verse],
  'supportiveMessage' : string,
  'actionStep' : string,
  'followUpQuestions' : Array<string>,
}
export type Mood = { 'sad' : null } |
  { 'anxious' : null } |
  { 'angry' : null } |
  { 'calm' : null } |
  { 'lost' : null } |
  { 'motivated' : null };
export interface Verse {
  'hindiMeaning' : string,
  'verse' : bigint,
  'actionStep' : string,
  'englishMeaning' : string,
  'chapter' : bigint,
  'genZKrishnaInterpretation' : string,
  'sanskrit' : string,
}
export interface _SERVICE {
  'getAllChapters' : ActorMethod<[], Array<Chapter>>,
  'getChatbotResponse' : ActorMethod<
    [string, [] | [Mood], Array<string>],
    ChatbotResponse
  >,
  'getCuratedVersesByMood' : ActorMethod<[Mood], Array<Verse>>,
  'getMoodTaglines' : ActorMethod<[], Array<[Mood, string]>>,
  'getTodaysVerse' : ActorMethod<[], [] | [Verse]>,
  'getVerse' : ActorMethod<[bigint, bigint], [] | [Verse]>,
  'getVersesByChapter' : ActorMethod<[bigint], Array<Verse>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];