/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Verse {
    hindiMeaning: string;
    verse: bigint;
    actionStep: string;
    englishMeaning: string;
    chapter: bigint;
    genZKrishnaInterpretation: string;
    sanskrit: string;
}
export interface ChatbotResponse {
    selectedVerse?: Verse;
    supportiveMessage: string;
    actionStep: string;
    followUpQuestions: Array<string>;
}
export interface Chapter {
    sanskritSubtitle: string;
    englishTitle: string;
    verseCount: bigint;
    keyInsights: Array<string>;
    summary: string;
    number: bigint;
}
export enum Mood {
    sad = "sad",
    anxious = "anxious",
    angry = "angry",
    calm = "calm",
    lost = "lost",
    motivated = "motivated"
}
export interface backendInterface {
    getAllChapters(): Promise<Array<Chapter>>;
    getChatbotResponse(userMessage: string, mood: Mood | null, _sessionHistory: Array<string>): Promise<ChatbotResponse>;
    getCuratedVersesByMood(mood: Mood): Promise<Array<Verse>>;
    getMoodTaglines(): Promise<Array<[Mood, string]>>;
    getTodaysVerse(): Promise<Verse | null>;
    getVerse(chapter: bigint, verse: bigint): Promise<Verse | null>;
    getVersesByChapter(chapterNumber: bigint): Promise<Array<Verse>>;
}
import type { ChatbotResponse as _ChatbotResponse, Mood as _Mood, Verse as _Verse } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllChapters(): Promise<Array<Chapter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChapters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChapters();
            return result;
        }
    }
    async getChatbotResponse(arg0: string, arg1: Mood | null, arg2: Array<string>): Promise<ChatbotResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatbotResponse(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_ChatbotResponse_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatbotResponse(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_ChatbotResponse_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCuratedVersesByMood(arg0: Mood): Promise<Array<Verse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCuratedVersesByMood(to_candid_Mood_n2(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCuratedVersesByMood(to_candid_Mood_n2(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getMoodTaglines(): Promise<Array<[Mood, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMoodTaglines();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMoodTaglines();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodaysVerse(): Promise<Verse | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodaysVerse();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodaysVerse();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVerse(arg0: bigint, arg1: bigint): Promise<Verse | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVerse(arg0, arg1);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVerse(arg0, arg1);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVersesByChapter(arg0: bigint): Promise<Array<Verse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVersesByChapter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVersesByChapter(arg0);
            return result;
        }
    }
}
function from_candid_ChatbotResponse_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatbotResponse): ChatbotResponse {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Mood_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Mood): Mood {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Verse]): Verse | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    selectedVerse: [] | [_Verse];
    supportiveMessage: string;
    actionStep: string;
    followUpQuestions: Array<string>;
}): {
    selectedVerse?: Verse;
    supportiveMessage: string;
    actionStep: string;
    followUpQuestions: Array<string>;
} {
    return {
        selectedVerse: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.selectedVerse)),
        supportiveMessage: value.supportiveMessage,
        actionStep: value.actionStep,
        followUpQuestions: value.followUpQuestions
    };
}
function from_candid_tuple_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Mood, string]): [Mood, string] {
    return [
        from_candid_Mood_n9(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sad: null;
} | {
    anxious: null;
} | {
    angry: null;
} | {
    calm: null;
} | {
    lost: null;
} | {
    motivated: null;
}): Mood {
    return "sad" in value ? Mood.sad : "anxious" in value ? Mood.anxious : "angry" in value ? Mood.angry : "calm" in value ? Mood.calm : "lost" in value ? Mood.lost : "motivated" in value ? Mood.motivated : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Mood, string]>): Array<[Mood, string]> {
    return value.map((x)=>from_candid_tuple_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Mood_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mood): _Mood {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mood | null): [] | [_Mood] {
    return value === null ? candid_none() : candid_some(to_candid_Mood_n2(_uploadFile, _downloadFile, value));
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mood): {
    sad: null;
} | {
    anxious: null;
} | {
    angry: null;
} | {
    calm: null;
} | {
    lost: null;
} | {
    motivated: null;
} {
    return value == Mood.sad ? {
        sad: null
    } : value == Mood.anxious ? {
        anxious: null
    } : value == Mood.angry ? {
        angry: null
    } : value == Mood.calm ? {
        calm: null
    } : value == Mood.lost ? {
        lost: null
    } : value == Mood.motivated ? {
        motivated: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
